version: '3.8'

services:
  ts-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - .env
    depends_on:
      - py-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  py-service:
    build: 
      context: ../skill-map-ai-service  # Adjust path to your Python microservice
    ports:
      - "8000:8000"
    environment:
      - .env
networks:
  default:
    driver: bridge